name: Build and verify

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Run tests
        run: dotnet fsi build.fsx -- -p test
